name = "DiskBackedDicts"
uuid = "a606033f-14ee-4438-ae87-3b404a2b735d"
authors = ["Jan Weidner <jw3126@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
julia = "1"
JLD2 = "0.4.22"
ArgCheck = "1, 2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
